# 由source 指向 target
source_lidar_topic: /scan1
target_lidar_topic: /scan2

source_lidar_frame: laser2
target_lidar_frame: laser1

icp_score: 5.386

# 在base_link坐标系下主雷达的坐标
main_to_base_transform_x: 0.37
main_to_base_transform_y: 0.25
main_to_base_transform_row: 0 # 反装为负
main_to_base_transform_yaw: 0
